config/routes.rb
Educar::Application.routes.draw do

  resources :comments

  resources :itens

  get "questoes/dynamic_select_assuntos/:id", :controller => 'questoes', :action => 'dynamic_select_assuntos'
  post "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  get "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  resources :questoes

  resources :concursos do
    get :autocomplete_banca_nome, :on => :collection
  end
  resources :concursos

  resources :assuntos

  resources :materias

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  match 'home/burndown'

  post "home/dynamic_add_comment", :controller => "home", :action => "dynamic_add_comment"
  post "home/dynamic_get_comment", :controller => "home", :action => "dynamic_get_comment"
  match 'home/resolvendo'
  get "home/dynamic_select_item/:id", :controller => 'home', :action => 'dynamic_select_item'

  root :to => 'home#index'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  texto      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  ancestry   :string(255)
#  questao_id :integer
#  user_id    :integer
#

class Comment < ActiveRecord::Base
  attr_accessible :texto, :questao_id, :user_id
  belongs_to :questao
  belongs_to :user
  has_ancestry

  validates_presence_of :user
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user! 
  before_filter :verify_comment_owner, :only => [:show, :edit, :update, :destroy]
  load_and_authorize_resource 

  def verify_comment_owner
    comment = Comment.find(params[:id])
    if comment.blank?
      return redirect_to root_url, :alert => 'Acesso negado!'
    end  
    if current_user != comment.user
      return redirect_to root_url, :alert => 'Acesso negado!'
    end
  end

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.first(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html { render :layout => false}# new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, :html => { :class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :texto, :as => :text, :input_html => {:cols => 60, :rows => 8} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:texto) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment)  %></td>
        <td><%= comment.texto  %></td>
        <td>
              <%= link_to image_tag('edit.png'), edit_comment_path(comment), :class => 'quick-edit',
                      :title => 'editar' %>
              <%= link_to image_tag('delete.png'), comment_path(comment), :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", 
                          :default => 'Você tem certeza?')) },
                          :class => '', :title => 'deletar' %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn' %>

app/views/comments/new.html.erb
<div style="width:300px; height:370px; padding-top:0px;">
	<%- model_class = Comment -%>
	<div class="page-header">
	  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
	                                 :default => "Novo #{model_class.model_name.human}") %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Texto:</b>
  <%= @comment.texto %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>