config/routes.rb
Educar::Application.routes.draw do

  resources :comments

  resources :itens

  get "questoes/dynamic_select_assuntos/:id", :controller => 'questoes', :action => 'dynamic_select_assuntos'
  post "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  get "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  resources :questoes

  resources :concursos do
    get :autocomplete_banca_nome, :on => :collection
  end
  resources :concursos

  resources :assuntos

  resources :materias

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  match 'home/burndown'

  post "home/dynamic_add_comment", :controller => "home", :action => "dynamic_add_comment"
  post "home/dynamic_get_comment", :controller => "home", :action => "dynamic_get_comment"
  match 'home/resolvendo'
  get "home/dynamic_select_item/:id", :controller => 'home', :action => 'dynamic_select_item'

  root :to => 'home#index'

end

app/controllers/questoes_controller.rb
#encoding=utf-8
class QuestoesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except => [:dynamic_select_assuntos, :dynamic_add_item]
  helper_method :sort_column, :sort_direction
  
  # GET /questoes
  # GET /questoes.json
  def index
    @questoes = Questao.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questoes }
    end
  end

  # GET /questoes/1
  # GET /questoes/1.json
  def show
    @questao = Questao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questao }
    end
  end

  # GET /questoes/new
  # GET /questoes/new.json
  def new
    @questao = Questao.new
    session['questao_itens'] = Array.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questao }
    end
  end

  # GET /questoes/1/edit
  def edit
    @questao = Questao.find(params[:id])
    session['questao_itens'] = @questao.itens.order(:id).collect{|i| i.desc}
  end

  # POST /questoes
  # POST /questoes.json
  def create
    @questao = Questao.new(params[:questao])
    @questao.user = current_user
    @questao.questao_itens = session['questao_itens']

    respond_to do |format|
      if @questao.save
        session['questao_itens'].each do |i|
          @questao.itens << Item.new(:desc => i, :questao_id => @questao.id)
        end
        @questao.save
        session['questao_itens'] = nil
        format.html { redirect_to @questao, notice: 'Questão criada com sucesso.' }
        format.json { render json: @questao, status: :created, location: @questao }
      else
        puts @questao.errors.to_xml
        format.html { render action: "new" }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questoes/1
  # PUT /questoes/1.json
  def update
    @questao = Questao.find(params[:id])
    @questao.questao_itens = session['questao_itens']

    respond_to do |format|
      if @questao.update_attributes(params[:questao])
        format.html { redirect_to @questao, notice: 'Questão atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questoes/1
  # DELETE /questoes/1.json
  def destroy
    @questao = Questao.find(params[:id])
    @questao.destroy

    respond_to do |format|
      format.html { redirect_to questoes_url }
      format.json { head :no_content }
    end
  end

  def dynamic_select_assuntos
    if can? :create, Questao
      @materia = Materia.find(params[:id])
    end 
    respond_to do |format|
      format.js
    end
  end

  def dynamic_add_item

    @itens = session['questao_itens']

    unless params['questao_id'].blank?
      @questao = Questao.find(params['questao_id'].to_i)
      unless params['op'].blank?  
        unless @questao.itens.order(:id)[params['item_index'].to_i].blank?
          @questao.itens.delete @questao.itens.order(:id)[params['item_index'].to_i]
          @questao.save
        end
      end
    end

    unless params['op'].blank?
      @itens.delete @itens[params['item_index'].to_i]
    else
      if @itens.include? params['item_desc']
        @alert = 'já existe um item com este valor'
      else
        @itens << params['item_desc']
        unless @questao.blank?
          @questao.itens << Item.new(:desc => params['item_desc'], :questao_id => @questao.id)
        end
      end
    end  
    
    respond_to do |format|
      format.js
    end
  end


  private
  
  def sort_column
    Questao.column_names.include?(params[:sort]) ? params[:sort] : "materia_id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/questoes_helper.rb
module QuestoesHelper
	
	def get_tipo(tipo)
		if tipo == "M"
			"Multipla Escolha"
		elsif tipo == "C"
			"Certa / Errada"
		else
			"Outro"
		end
	end

end

app/views/questoes/_form.html.erb
<%= hidden_field_tag 'questao_id', params[:id] %>
<%= simple_form_for @questao, :html => { :class => 'form-horizontal' } do |f| %>
  <%= tinymce_assets %>
  <%= tinymce %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
	  <%= f.association :concurso, :input_html => { :style => "width: auto" }, collection: Concurso.ordered %>
    <%= f.association :materia, :input_html => { :style => "width: auto" } %>

    <% if @questao.materia.blank? %>
      <%= f.association :assunto, :collection => [], :input_html => { :style => "width: auto" } %>
    <% else %>
      <%= f.association :assunto, :collection => @questao.materia.assuntos.sort {|a,b| a.name_with_parent <=> b.name_with_parent}.collect{|a| [a.name_with_parent, a.id]}, :input_html => { :style => "width: auto" } %>
    <% end %>

    <%= f.input :tipo, :collection => [['Múltipla Escolha', 'M'], ['Certa / Errada', 'C']], :include_blank => false %>
	  
    <%= f.input :gabarito, :input_html => { :style => "width: 100px;" }, :hint => 'CCEE para questões de certo/errado e A,B,C,D ou E para múltipla escolha...' %>

	  <%= f.input :texto, :as => :text, :input_html => {:rows => 8, :cols => 80, :class => 'tinymce' }, :hint => 'coloque aqui a pergunta...' %>

    <div class="control-group text optional">
      <label for="questao_item" class="text optional control-label">
        Adicionar Item
      </label>
      <div class="controls">
        <textarea rows="4" name="dinamic_questao_item" id="questao_item" cols="80" class="text optional tinymce"></textarea>
        <input id="add_item" value="Criar Item" name="commit" class="btn">
        <p class="help-block">
          coloque aqui os itens...
        </p>
      </div>
    </div>
    
    <div id="questao_itens">

      <% unless session['questao_itens'].blank? %>
        <% session['questao_itens'].each.with_index do |i,index| %>
          <div class="control-group text optional">
            <label for="questao_item" class="text optional control-label">
              Item <%= value_item index %>
            </label>
            <div class="controls" style="padding-top:5px; margin-bottom:5px;">
              <a onClick="javascript:delete_item_temp(<%= index %>); " href="javascript:void(0)"> 
                <i style="float:left; margin-right:5px;" class="icon-remove"></i>
              </a>
              <% unless @questao.itens[index].blank? %>
                <a href="<%= edit_item_path(@questao.itens[index].id)%>">
                  <i style="float:left; margin-right:5px;" class="icon-edit"></i>
                </a>
              <% end %>
              <%= raw i %> 
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questoes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/questoes/dynamic_add_item.js.erb
$('#questao_itens').empty();

var html = '';

<% @itens.each.with_index do |i,index| %>

	html += '<div class="control-group text optional">'
	html += '<label for="questao_item" class="text optional control-label">'
	html += 'Item <%= value_item index %>'
	html += '</label>'
	html += '<div class="controls" style="padding-top:5px;"> '
	html += '<a onClick="javascript:delete_item_temp(<%= index %>); " href="javascript:void(0)"> '
	html += '<i style="float:left; margin-right:5px;" class="icon-remove"></i></a> '
	<% unless @questao.blank? %>
	<% unless @questao.itens.order(:id)[index].blank? %>
	  html += '<a href="<%= edit_item_path(@questao.itens.order(:id)[index].id)%>"> '
	  	html += '<i style="float:left; margin-right:5px;" class="icon-edit"></i> '
      html += '</a> '
    <% end %>
    <% end %>
	html += '<%= raw i %>'
	html += '</div>'
	html += '</div>'

<% end %>

$('#questao_itens').html(html);

<% unless @alert.blank? %>
	alert('<%= @alert %>');
<% end %>

app/views/questoes/dynamic_select_assuntos.js.erb
$('#questao_assunto_id').empty();

<% unless @materia.blank? %>

	<% for assunto in @materia.assuntos.sort {|a,b| a.name_with_parent <=> b.name_with_parent} %>

		$('#questao_assunto_id').append($("<option></option>").attr("value",<%= assunto.id %>).text('<%= escape_javascript(assunto.name_with_parent) %>'));

	<% end %>

<% end %>

app/views/questoes/edit.html.erb
<%- model_class = Questao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questoes/index.html.erb
<%- model_class = Questao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(:count => 2) %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "id", model_class.human_attribute_name(:id) %></th>
      <th><%= sortable "materia_id", model_class.human_attribute_name(:materia_id) %></th>
      <th><%= sortable "concurso_id", model_class.human_attribute_name(:concurso_id) %></th>
      <th><%= sortable "assunto_id", model_class.human_attribute_name(:assunto_id) %></th>
      <th><%= sortable "tipo" %></th>
      <th><%= model_class.human_attribute_name(:gabarito) %></th>
      <th><%= model_class.human_attribute_name(:texto) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questoes.each do |questao| %>
      <tr>
        <td><%= link_to questao.id, questao_path(questao) %></td>
        <td><%= questao.materia.nome %></td>
        <td><%= questao.concurso.nome %></td>
        <td><%= questao.assunto.nome %></td>
        <td>
          <abbr title="<%= raw escape_javascript(get_tipo questao.tipo) %>">
            <%= raw questao.tipo %>
          </abbr>
        </td>
        <td><%= questao.gabarito %></td>
        <td>
          <abbr title="<%= escape_javascript(ActionController::Base.helpers.strip_tags(questao.texto.strip).gsub('"','').squish) %>">
              <%= ActionController::Base.helpers.strip_tags(questao.texto.strip).first(16) + '...' %> 
          </abbr> 
        </td>
        <td style="width: 53px;">
          <%= link_to new_item_path(:questao => questao.id), :class => "icon-item", :title => "adicionar item" do %>
            <i class="icon-plus"></i>
          <% end %>
          <%= link_to image_tag('edit.png'), edit_questao_path(questao), :class => 'quick-edit',:title => 'editar' %>
          <%= link_to image_tag('delete.png'), questao_path(questao), :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", 
                      :default => 'Você tem certeza?')) },
                      :class => '', :title => 'deletar' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
  <%= will_paginate @questoes %>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_questao_path,
            :class => 'btn' %>

app/views/questoes/new.html.erb
<%- model_class = Questao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Nova #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questoes/show.html.erb
<%- model_class = Questao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human(:count => 1) %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:materia_id) %>:</strong></dt>
  <dd><%= @questao.materia.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:concurso_id) %>:</strong></dt>
  <dd><%= @questao.concurso.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:assunto_id) %>:</strong></dt>
  <dd><%= @questao.assunto.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gabarito) %>:</strong></dt>
  <dd><%= @questao.gabarito %></dd>
  <dt><strong><%= model_class.human_attribute_name(:texto) %>:</strong></dt>
  <dd><%= raw @questao.texto %></dd>
</dl>

<dl class="dl-horizontal">
  <% @questao.itens.sort.each.with_index do |item, index| %>
    <dt><strong>Item <%= value_item index %>:</strong></dt>
    <dd><%= (link_to (raw item.desc), item_path(item)) %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              questoes_path, :class => 'btn'  %>
  <%= link_to t('.new', :default => t("helpers.links.new")+" - Item"),
            new_item_path(:questao => @questao.id), :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_questao_path(@questao), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              questao_path(@questao),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
              :class => 'btn' %>
</div>