config/routes.rb
Educar::Application.routes.draw do

  resources :comments

  resources :itens

  get "questoes/dynamic_select_assuntos/:id", :controller => 'questoes', :action => 'dynamic_select_assuntos'
  post "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  get "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  resources :questoes

  resources :concursos do
    get :autocomplete_banca_nome, :on => :collection
  end
  resources :concursos

  resources :assuntos

  resources :materias

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  match 'home/burndown'

  post "home/dynamic_add_comment", :controller => "home", :action => "dynamic_add_comment"
  post "home/dynamic_get_comment", :controller => "home", :action => "dynamic_get_comment"
  match 'home/resolvendo'
  get "home/dynamic_select_item/:id", :controller => 'home', :action => 'dynamic_select_item'

  root :to => 'home#index'

end

app/models/concurso.rb
# == Schema Information
#
# Table name: concursos
#
#  id         :integer          not null, primary key
#  nome       :string(255)
#  ano        :integer
#  cargo      :string(255)
#  edital     :string(255)
#  gabarito   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  banca_id   :integer
#  prova      :string(255)
#

class Concurso < ActiveRecord::Base
  attr_accessible :ano, :cargo, :edital, :prova, :gabarito, :nome, :banca_id, :banca

  validates_presence_of :nome, :ano, :cargo

  has_many :questoes, :dependent => :destroy
  belongs_to :banca

  scope :ordered, order('ano DESC, nome ASC, cargo ASC')

  mount_uploader :edital, PdfUploader
  mount_uploader :prova, PdfUploader
  mount_uploader :gabarito, PdfUploader

  def name
  	("#{self.ano} - #{self.nome} - #{self.cargo}".size > 70) ? "#{self.ano} - #{self.nome} - #{self.cargo}".first(70).upcase + "..." : "#{self.ano} - #{self.nome} - #{self.cargo}".upcase
  end

  def nome=(val)
    self[:nome] = val.upcase
  end
  
  def cargo=(val)
    self[:cargo] = val.upcase
  end

end

app/controllers/concursos_controller.rb
class ConcursosController < ApplicationController
  before_filter :authenticate_user! 
  before_filter :check_banca, :only=>[:create, :update]
  load_and_authorize_resource 
  autocomplete :banca, :nome
  

  def check_banca
    banca ||= Banca.find_by_nome(params[:concurso][:banca])
    if banca.blank? and !params[:concurso][:banca].blank?
      banca = Banca.create(:nome => params[:concurso][:banca])
    end
    unless banca.blank?
      params[:concurso][:banca_id] = banca.id
    end
    params[:concurso].delete "banca"
    puts params
  end

  # GET /concursos
  # GET /concursos.json
  def index
    @concursos = Concurso.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concursos }
    end
  end

  # GET /concursos/1
  # GET /concursos/1.json
  def show
    @concurso = Concurso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concurso }
    end
  end

  # GET /concursos/new
  # GET /concursos/new.json
  def new
    @concurso = Concurso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concurso }
    end
  end

  # GET /concursos/1/edit
  def edit
    @concurso = Concurso.find(params[:id])
  end

  # POST /concursos
  # POST /concursos.json
  def create
    @concurso = Concurso.new(params[:concurso])

    respond_to do |format|
      if @concurso.save
        format.html { redirect_to @concurso, notice: 'Concurso criado com sucesso.' }
        format.json { render json: @concurso, status: :created, location: @concurso }
      else
        format.html { render action: "new" }
        format.json { render json: @concurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concursos/1
  # PUT /concursos/1.json
  def update
    @concurso = Concurso.find(params[:id])

    respond_to do |format|
      if @concurso.update_attributes(params[:concurso])
        format.html { redirect_to @concurso, notice: 'Concurso atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concursos/1
  # DELETE /concursos/1.json
  def destroy
    @concurso = Concurso.find(params[:id])
    @concurso.destroy

    respond_to do |format|
      format.html { redirect_to concursos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/concursos_helper.rb
module ConcursosHelper
end

app/views/concursos/_form.html.erb
<%= simple_form_for @concurso, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :banca, :url => autocomplete_banca_nome_concursos_path, :as => :autocomplete %>
    <%= f.input :banca_id, :as => 'hidden' %>
    <%= f.input :ano, :collection => 2000..(Date.today.year+1), :selected => Date.today.year %>
    <%= f.input :cargo %>
    <%= f.input :edital, :as => 'file' %>
    <%= f.input :prova, :as => 'file' %>
    <%= f.input :gabarito, :as => 'file' %>
  </div>
  
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                concursos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/concursos/edit.html.erb
<%- model_class = Concurso -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/concursos/index.html.erb
<%- model_class = Concurso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:banca) %></th>
      <th><%= model_class.human_attribute_name(:ano) %></th>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:edital) %></th>
      <th><%= model_class.human_attribute_name(:prova) %></th>
      <th><%= model_class.human_attribute_name(:gabarito) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @concursos.each do |concurso| %>
      <tr>
        <td><%= link_to concurso.id, concurso_path(concurso) %></td>
        <td><%= concurso.nome %></td>
        <td><%= concurso.banca %></td>
        <td><%= concurso.ano %></td>
        <td><%= concurso.cargo %></td>
        <td><%= link_to_unless concurso.edital.url.blank?, (concurso.edital.url.blank?) ? '' : 'EDITAL', concurso.edital.url %></td>
        <td><%= link_to_unless concurso.prova.url.blank?, (concurso.prova.url.blank?) ? '' : 'PROVA', concurso.prova.url %></td>
        <td><%= link_to_unless concurso.gabarito.url.blank?, (concurso.gabarito.url.blank?) ? '' : 'GABARITO', concurso.gabarito.url %></td>
        <td>
          <%= link_to image_tag('edit.png'), edit_concurso_path(concurso), :class => 'quick-edit',
                  :title => 'editar' %>
          <%= link_to image_tag('delete.png'), concurso_path(concurso), :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", 
                      :default => 'Você tem certeza?')) },
                      :class => '', :title => 'deletar' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_concurso_path,
            :class => 'btn' %>

app/views/concursos/new.html.erb
<%- model_class = Concurso -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Novo #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/concursos/show.html.erb
<%- model_class = Concurso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @concurso.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:banca) %>:</strong></dt>
  <dd><%= @concurso.banca.nome if @concurso.banca %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ano) %>:</strong></dt>
  <dd><%= @concurso.ano %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cargo) %>:</strong></dt>
  <dd><%= @concurso.cargo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edital) %>:</strong></dt>
  <dd><%= @concurso.edital %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prova) %>:</strong></dt>
  <dd><%= @concurso.prova %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gabarito) %>:</strong></dt>
  <dd><%= @concurso.gabarito %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              concursos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_concurso_path(@concurso), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              concurso_path(@concurso),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
              :class => 'btn' %>
</div>