config/routes.rb
Educar::Application.routes.draw do

  resources :comments

  resources :itens

  get "questoes/dynamic_select_assuntos/:id", :controller => 'questoes', :action => 'dynamic_select_assuntos'
  post "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  get "questoes/dynamic_add_item", :controller => 'questoes', :action => 'dynamic_add_item'
  resources :questoes

  resources :concursos do
    get :autocomplete_banca_nome, :on => :collection
  end
  resources :concursos

  resources :assuntos

  resources :materias

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  match 'home/burndown'

  post "home/dynamic_add_comment", :controller => "home", :action => "dynamic_add_comment"
  post "home/dynamic_get_comment", :controller => "home", :action => "dynamic_get_comment"
  match 'home/resolvendo'
  get "home/dynamic_select_item/:id", :controller => 'home', :action => 'dynamic_select_item'

  root :to => 'home#index'

end

app/views/layouts/_imports.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!-- images/apple-touch-icon-114x114-precomposed.png -->
    <%= favicon_link_tag 'ac.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'ac.png', :rel => 'shortcut icon', :size => '32x32' %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6294827-3', 'aprenderconcursos.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_materias.html.erb
<ul class="nav nav-list">
  <li class="nav-header">Materias</li>
  <% @materiasHome.each do |m|%>
  	<li class="<%= materia_active m.id%>">
  		<%= link_to m.nome.titleize, root_path(:materia_id => m.id)%>
  	</li>
  <% end %>
  <% if @materiasHome.blank? %>
  	<li class="active"><a href="#">Não há cadastro</a></li>
  <% end %>
  
</ul>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
<a class="brand" href="/">Educar</a>
<div class="container nav-collapse">
	<ul class="nav pull-right">
		<li><%= link_to 'Home', '/' %></li>
		<% if user_signed_in? %>
			<li><%= link_to 'Editar conta', edit_user_registration_path %></li>
		    <% if current_user.has_role? 'admin' %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Gerenciar
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to 'Assuntos', assuntos_path %></li>
						<li><%= link_to 'Concursos', concursos_path %></li>
						<li><%= link_to 'Materias', materias_path %></li>
						<li><%= link_to 'Questões', questoes_path %></li>
					</ul>
				</li>
			<% end %>
		    <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
		<% else %>
		    <li><%= link_to 'Login', new_user_session_path %></li>
		    <li><%= link_to 'Cadastrar', new_user_registration_path %></li>
		    <li><%= link_to image_tag('facebook_32.png'), user_omniauth_authorize_path(:facebook) %></li>
		<% end %>
	</ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Educar" %></title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/imports' %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>

	<div class="container-fluid">
      <div class="row-fluid">
        <% unless params[:controller].to_s.include? 'devise'%>
          <div class="span3">
            <div class="span10">
              <div class="well sidebar-nav">
                <%= render 'layouts/materias' %>
              </div><!--/.well -->
            </div>
          </div><!--/span-->
          <div class="span9" style="margin-left:0px;">
            <div class="<%= default_class(yield(:class)) %>">
              <%= bootstrap_flash %>
              <%= yield %>
            </div>
          </div><!--/span-->
        <% else %>
          <div class="span12">
            <div class="span6 offset3" style="margin-bottom: 20 px">
              <%= bootstrap_flash %>
              <%= yield %>
            </div>
          </div>
        <% end %>
        
      </div><!--/row-->

      <hr>
      <%= debug(params) if Rails.env.development? %>
      <%= debug(session) if Rails.env.development? %>
      <%= debug current_user if Rails.env.development? %>
      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>